# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e14f5240bc5d07cdf9b253352752e691e9d47c1daa588fc2580078e60e20ae9d8278efde4119326c0380ff06e424257a266980e2f5f831b79c119be98161e189

test:
  secret_key_base: 2e89a9a1a5db1abe17ce72601a338442b249243da7e780c3f4fdcc86a18d60bd19bad05804be8d171a64bb6dde3ff5dea4d2aa6ee9e3b712017866112a1fc576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
